### ISSUE TITLE
test cases failing due to incorrect DB permissions

### ISSUE THREAD

**Issue by jessemtso** [yedi/garpr#16]
in vagrant env. an example

======================================================================
ERROR: test suite for <class 'test.test_dao.TestDAO'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/local/lib/python2.7/dist-packages/nose/util.py", line 470, in try_run
    return func()
  File "/home/vagrant/test/test_dao.py", line 16, in setUpClass
    MongoClient().drop_database(DATABASE_NAME)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 1051, in drop_database
    read_preference=ReadPreference.PRIMARY)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 481, in command
    codec_options, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 393, in _command
    allowable_errors)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 213, in command
    read_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/network.py", line 99, in command
    helpers._check_command_response(response_doc, None, allowable_errors)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 196, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailure: not authorized on garpr_test to execute command { dropDatabase: 1 }

**Comment by acoulon99** [comment]
on it!

**Comment by acoulon99** [comment]
I think it's close, but I'm not really familiar with python enough to quite tell what that output object is. Do you know know @jessemtso ?

this: `print(dao.get_players_with_similar_alias("1 1 gar")[0])`
outputs this: `57536dba81caa3401ca4010d gaR {u'norcal': '(25.000, 8.333)', u'texas': '(25.000, 8.333)'} [u'gar', u'garr'] [u'norcal', u'texas']`
however, this test fails:
`self.assertTrue("gaR" in dao.get_players_with_similar_alias("1 1 gar"))`
